<a href="https://colab.research.google.com/github/CPukszta/BI-BE-CS-183-2023/blob/main/HW8/problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is the notebook for calculating probabiltites for question 1. Code will have some comments but may be more sparse :(


In [1]:
import numpy as np
import scipy.io as sio
import pandas as pd
import matplotlib.pyplot as plt #Can use other plotting packages like seaborn

Lets start by computing the probability of getting the sequence ACG as a result of every possible combination of hidden state

In [6]:
#define our s and t matrix
s = np.array([[0.8,0.2],[0.05,0.95]])
t = np.array([[0.2,0.5,0.1,0.2],[0.1,0.25,0.25,0.4]])

In [43]:
# define a matrix of all the possible combinations of hidden states
HS_mat = np.matrix([[0,0,0],[0,0,1],[0,1,1],[1,1,1],[1,1,0],[1,0,0]])
print(HS_mat)

#lets now compute the probaility of each of these hidden states occuring
hidden_state_prob = np.zeros(np.shape(HS_mat))
hidden_state_prob[:,0] = 0.5

print(hidden_state_prob)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 0]]
[[0.5 0.  0. ]
 [0.5 0.  0. ]
 [0.5 0.  0. ]
 [0.5 0.  0. ]
 [0.5 0.  0. ]
 [0.5 0.  0. ]]


In [49]:
#def a function to give the p(state change between t-1 and t)
def hiddenstate_step(s,state_old,state_new):
  t_prob = np.zeros(np.shape(state_old))
  i = 0
  while i < len(t_prob):
    if (state_old[i] == 0 and state_new[i]== 0):
      t_prob[i] = s[0,0]
    if (state_old[i] == 0 and state_new[i]==1):
      t_prob[i] = s[0,1]
    if (state_old[i] == 1 and state_new[i]==0):
      t_prob[i] = s[1,0]
    if (state_old[i] == 1 and state_new[i]==1):
      t_prob[i] = s[1,1]
    i += 1

  return t_prob[:,0]

In [50]:
for i in range(1,np.shape(HS_mat)[1]):
  hidden_state_prob[:,i] = hiddenstate_step(s,HS_mat[:,i-1],HS_mat[:,i])

print(hidden_state_prob)

[[0.5  0.8  0.8 ]
 [0.5  0.8  0.2 ]
 [0.5  0.2  0.95]
 [0.5  0.95 0.95]
 [0.5  0.95 0.05]
 [0.5  0.05 0.8 ]]


In [60]:
# now lets def a function to give the p(a given string value given the current state)
def p_func(t,curr_state,val):
  #order of nucleotides
  nuc = 'ACTG'
  #index of given nucleotide
  val_ind = nuc.index(val)

  t_prob = np.zeros(np.shape(curr_state))

  i = 0
  while i < len(curr_state):
    if (curr_state[i] == 0):
      t_prob[i] = t[0,val_ind]
    if (curr_state[i] == 1):
      t_prob[i] = t[1,val_ind]
    i += 1

  return t_prob[:,0]

In [66]:
#lets run our function to get the probaility of getting the desired nucleotide at each time point
observation_prob = np.zeros(np.shape(HS_mat))

string = "ACG"

for i in range(np.shape(HS_mat)[1]):
  observation_prob[:,i] = p_func(t,HS_mat[:,i],string[i])

print(observation_prob)

[[0.2  0.5  0.2 ]
 [0.2  0.5  0.4 ]
 [0.2  0.25 0.4 ]
 [0.1  0.25 0.4 ]
 [0.1  0.25 0.2 ]
 [0.1  0.5  0.2 ]]


In [70]:
#now we can calculate the probaility that each sequence of hidden states gave the string ACG
#by multiplying everything together!
prob_ACG = np.prod(hidden_state_prob*observation_prob,axis=1)

print(prob_ACG)

max_HSS = HS_mat[np.where(prob_ACG == np.max(prob_ACG)),:]
print("the sequence of hidden states that gives the highest prob of getting ACG is:", max_HSS)

[0.0064     0.0032     0.0019     0.0045125  0.00011875 0.0002    ]
the sequence of hidden states that gives the highest prob of getting ACG is: [[[0 0 0]]]


In [75]:
#the overall prob of getting this sequence is the intersection of these events
#thus lets add these probailities
#this is the calcualtion for part C

p_ACG = np.sum(prob_ACG)

print("the prob of getting ACG is:",p_ACG)

the prob of getting ACG is: 0.016331250000000005


As we can see, all the sequences give a non-zero probability of getting the sequence ACG.

Futhurmore, the sequence of hidden states: 0,0,0 gives the highest probability!

In [78]:
#lets find the most probable hidden state sequence:
prob_HSS_mat = np.prod(hidden_state_prob,axis=1)

prob_HSS = HS_mat[np.where(prob_HSS_mat == np.max(prob_HSS_mat)),:]

print("the most probable hidden state sequence is:", prob_HSS)
print("the prob of getting ACG from this hidden state sequence is:", 
      np.prod(observation_prob[np.where(prob_HSS_mat == np.max(prob_HSS_mat)),:]) )

the most probable hidden state sequence is: [[[1 1 1]]]
the prob of getting ACG from this hidden state sequence is: 0.010000000000000002
